package cenaflix;

import Dados.Filme;
import Dados.FilmeDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaPesquisaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisaCategoria
     */
    public TelaPesquisaCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilmes = new javax.swing.JTable();
        txtCategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNome.setText("Categoria:");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Pesquisa de Filmes");

        btnPesquisar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Lançamento", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFilmes);

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        atualizar2();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblFilmes;
    private javax.swing.JTextField txtCategoria;
    // End of variables declaration//GEN-END:variables
    
    private TelaInicial telaI;
    /**
     * Função criada para iniciar a tela de pesquisa a partir da tela inicial.
     * Essa função foi criada para chmar funções da tela de pesquisa ao inicia-la pela tela inicial
     * @param telainicial 
     */
    public void MostraTela(TelaInicial telainicial){
         this.telaI = telainicial;
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
         atualizar();
         setVisible(true);
     }
    
    
    private final String[] colunas = {"Id", "Nome", "Lançamento", "Categoria"};
    /**
     * Função utilizada para atualizar a tabela da tela de pesquisa com os dados do banco de dados SQL
     * ao clicar no botão de pesquisa
     */
    public void atualizar(){
        
        Connection conn = null;
        PreparedStatement st;
        ResultSet rs = null;
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cenaflix_bd", "root", "14728360Meub@nco");
            st = conn.prepareStatement("select id, nome, DATE_FORMAT(lancamento,'%d/%m/%Y') as lancamento, categoria from filmes");
            rs = st.executeQuery();
            while(rs.next()){
                String id = String.valueOf(rs.getString("id"));
                String[] linha = {id, rs.getString("nome"), rs.getString("lancamento"), rs.getString("categoria")};
                tabelaModelo.addRow(linha);
            }
            tblFilmes.setModel(tabelaModelo);
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Deu errado aqui, meu chapa: "+e.getMessage());
        }
        finally{
            txtCategoria.setText("");
        }
        
    }
    
    
    FilmeDao dao = new FilmeDao();
    /**
     * Atualiza a tela após inserir o nome da categoria
     */
    public void atualizar2(){
                
        Connection conn = null;
        PreparedStatement st;
        ResultSet rs = null;
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cenaflix_bd", "root", "14728360Meub@nco");
            st = conn.prepareStatement("select id, nome, DATE_FORMAT(lancamento,'%d/%m/%Y') as lancamento, categoria from filmes where categoria = ?");
            st.setString(1, txtCategoria.getText());
            rs = st.executeQuery();
            while(rs.next()){
                String id = String.valueOf(rs.getString("id"));
                String[] linha = {id, rs.getString("nome"), rs.getString("lancamento"), rs.getString("categoria")};
                tabelaModelo.addRow(linha);
            }
            tblFilmes.setModel(tabelaModelo);
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Deu errado aqui, meu chapa: "+e.getMessage());
        }
        finally{
            txtCategoria.setText("");
        }
        
    }
    
    
    

}
